# fly.toml app configuration file generated for instabid on 2024-11-03T00:45:13+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'instabid'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app'] 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
